### ISSUE TITLE
Update Rust to 1.68.2

### ISSUE THREAD

**Issue by Taaitaaiger** [JuliaPackaging/BinaryBuilderBase.jl#307]
There have been two patch releases since the release of Rust 1.68, the latter of which due to the leaked GitHub RSA host key. I'd also like to request a new release of this package so the sparse protocol is used when compiling Rust crates with BinaryBuilder.

I'd be happy to help keep Rust up-to-date and provide the necessary PRs, but I'll need some info about what needs to be done :)

**Comment by giordano** [comment]
The process for updating the toolchains at the moment isn't super simple and it requires building them locally and uploading the results as release artifacts in the Yggdrasil repository. You can see the instructions for updating the Rust toolchain in particular at https://github.com/JuliaPackaging/Yggdrasil/blob/1cd5e9c605176eadd25bc121525afb7f94742ac0/0_RootFS/Rust/build_tarballs.jl#L1-L9 (but note that this requires write access to the Yggdrasil repository). However, in the not-so-distant future we will hopefully have a more straightforward way to handle the toolchains, which should be built directly like all other jll packages, and so anyone will be able to contribute them by opening PRs to Yggdrasil.

I'm happy to update the Rust toolchain for the time being, it's just that for the next 7-10 days I don't think I'll have much time to take care of it because of other personal commitments.

In any case, if you know a bit Rust infrastructure it'd be great if you could take a look at https://github.com/rust-lang/rustup/issues/3116 which is preventing us from upgrading to the latest version of rustup. That'd be an awesome way to contribute to our toolchain!

**Comment by Taaitaaiger** [comment]
Thanks for the extra info! I had found the recipe for the Rust toolchain, but I expected I was missing something because it still referred to 1.65 while it was already updated to 1.68 here.

FWIW, when I tried to build JlrsLedger for 32-bits Windows locally yesterday, I got a different set of functions that could not be found. I should have some time this weekend to take a look.
